config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'static_pages#home'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:edit, :update]
  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'

  get 'user_password_resets/new'
  get 'user_password_resets/edit'

  resources :account_activations, only: [:edit]
  resources :user_password_resets, only: [:new, :create, :edit, :update]

  resources :items do
    resources :physical_videos, only: [:index]
  end

  resources :loans, only: [:index]

  resources :physical_item do
    resources :loans, only: [:new]
  end

  resources :loans, only: [:create]

  resources :videos, only: [:index, :show]

  namespace :admin do
    resources :videos, only: [:new, :create, :edit, :update]
    resources :locations, only: [:new, :create, :edit, :update]
  end

  namespace :administrator do
    resources :clients
    resources :users
    resources :items
    resources :videos
    resources :locations
    resources :cities
    resources :global_settings, only: [:edit, :update]
    resources :physical_items
    resources :physical_videos
    resources :loans
    resources :coordinates
  end

  resources :locations, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  belongs_to :item
  has_many :physical_items, through: :item
  has_many :locations, through: :physical_items

  validates :year, presence: true
  validates :released, presence: true
  validates :director, presence: true
  validates :actors, presence: true
  validates :writer, presence: true
  validates :genres, presence: true
  validates :category, presence: true
  validates :awards, presence: true
  validates :rated, presence: true
  validates :imdb_rating, presence: true
  validate :trailer_url, if: :valid_trailer_url?
  validate :poster_url, if: :valid_poster_url?
  validates :imdb_url, presence: true
  validate :imdb_url, if: :valid_imdb_url?

  paginates_per 12

  scope :search_name, lambda { |string|
    return nil if string.blank?

    terms = string.downcase.split(/\s+/)

    terms = terms.map do |e|
      ('%' + e.tr('*', '%') + '%').gsub(/%+/, '%')
    end
    num_or_conds = 1
    joins(:item).where(
      terms.map do |_term|
        '(LOWER(items.name) LIKE ?)'
      end.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  scope :filter_location, lambda { |string|
    return nil if string.blank?

    joins(:locations).where("locations.id = ?", string.to_i.to_s).distinct
  }

  scope :filter_year, lambda { |string|
    return nil if string.blank?

    where(year: string)
  }

  scope :search_genre, lambda { |string|
    return nil if string.blank?

    string = ('%' + string.tr('*', '%') + '%').gsub(/%+/, '%')
    where("genres LIKE ?", "#{string}%")
  }

  scope :search_actors, lambda { |string|
    return nil if string.blank?

    terms = string.downcase.split(/\s+/)

    terms = terms.map do |e|
      ('%' + e.tr('*', '%') + '%').gsub(/%+/, '%')
    end
    num_or_conds = 1
    where(
      terms.map do |_term|
        '(LOWER(actors) LIKE ?)'
      end.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  private

  def valid_poster_url?
    return true if poster_url.nil? || uri?(poster_url)
  end

  def valid_imdb_url?
    return true if uri?(imdb_url)
  end

  def valid_trailer_url?
    return true if trailer_url.nil? || uri?(trailer_url)
  end

  def uri?(string)
    uri = URI.parse(string)
    %w[http https].include?(uri.scheme)
  rescue URI::BadURIError
    false
  rescue URI::InvalidURIError
    false
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminsController
  def new
  end

  def create
    params = set_params
    @video = Video.new(video_params(params))
    @item = @video.build_item(item_params(params))
    if @video.save
      flash[:success] = 'Filmul a fost adaugat'
      redirect_to videos_url
    else
      flash.now[:danger] = 'Filmul nu a fost adaugat'
      render 'index'
    end
  end

  def edit
  end

  def update
  end


  def video_params(params)
    params.require(:video).permit(:year, :released, :director, :actors, :writer, :genres, :category, :awards, :rated, :imdb_rating, :imdb_url, :poster_url, :trailer_url, :language)
  end

  def item_params(params)
    params.require(:video).permit(:name)
  end

  def set_params
    movie = omdb(params[:video][:imdb_id])
    params[:video][:year] = movie.year
    params[:video][:released] = movie.released
    params[:video][:director] = movie.director
    params[:video][:actors] = movie.actors
    params[:video][:language] = movie.language
    params[:video][:rated] = movie.rated
    params[:video][:writer] = movie.writer
    params[:video][:genres] = movie.genre
    params[:video][:category] = movie.type
    params[:video][:awards] = movie.awards
    params[:video][:rated] = movie.rated
    params[:video][:imdb_rating] = movie.imdb_rating
    params[:video][:imdb_url] = "https://www.imdb.com/title/#{params[:video][:imdb_id]}/"
    params[:video][:poster_url] = movie.poster
    params[:video][:name] = movie.title
    params
  end

  def omdb(imdb_id)
    client = Omdb::Api::Client.new(api_key: ENV["OMDB_API"])
    client.find_by_id(imdb_id)
  end
end

app/controllers/administrator/videos_controller.rb
class Administrator::VideosController < AdminsController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /administrator/videos
  def index
    @q = Video.ransack(params[:q])
    @videos = @q.result.order(updated_at: :desc).page(params[:page])
  end

  # GET /administrator/videos/1
  def show
  end

  # GET /administrator/videos/new
  def new
    @video = Video.new
  end

  # GET /administrator/videos/1/edit
  def edit
  end

  # POST /administrator/videos
  def create
    @video = Video.new(video_params)

    if @video.save
      redirect_to [:administrator, @video], notice: 'Video was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /administrator/videos/1
  def update
    if @video.update(video_params)
      redirect_to [:administrator, @video], notice: 'Video was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /administrator/videos/1
  def destroy
    @video.destroy
    redirect_to administrator_videos_url, notice: 'Video was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def video_params
      params.require(:video).permit(:item_id, :year, :language, :released, :director, :actors, :writer, :genres, :category, :awards, :rated, :imdb_rating, :imdb_url, :trailer_url, :poster_url)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all.search_name(params[:name])
                       .filter_year(params[:year])
                       .search_genre(params[:genre])
                       .search_actors(params[:actors])
                       .filter_location(params[:locations]&.first)
    @locations = params[:locations]
    @videos = @videos.order(updated_at: :desc).page params[:page]
    flash[:warning] = 'Niciun videoclip nu corespunde filtrarii' if @videos.blank?
  end

  def show
    @video = Video.find(params[:id])
    @youtube_video = youtube_embed(@video.trailer_url) unless @video.trailer_url.blank?
  end

  private

  def filter_location(videos, location_id)
    return videos if location_id.blank?

    videos_filtered = {}
    videos.each do |video|
      video.item.physical_items.each do |physical_item|
        videos_filtered.push(video) if physical_item.locations.find_by(location_id: location_id)
      end
    end
    videos_filtered.uniq
  end

  def youtube_embed(youtube_url)
    uri = URI(youtube_url)
    params = CGI.parse(uri.query)

    "https://www.youtube.com/embed/#{params["v"].first}"
  end
end

app/helpers/admin/videos_helper.rb
module Admin::VideosHelper
end

app/helpers/administrator/videos_helper.rb
module Administrator::VideosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/index.html.erb
<div class="row">

  <div class="col-lg-3">
    <h1 class="my-4">Filme</h1>
    <% if admin? %>
    <%= button_to "Adauga filme", new_admin_video_path, method: :get, class: "btn btn-primary" %>
    <% end %>
    <br>
    <%= form_tag(videos_url, method: :get) do %>
      <div class="justify-content-center"> <%= submit_tag 'Aplica filtre', class: "btn btn-dark"%>
      <a href="<%= "#{videos_url}" %>" class="btn btn-outline-danger">Ignora filtre</a></div> <br>

      <div class="list-group">
        <div class="list-group-item">Titlu: <%= text_field_tag :name, nil, class: "form-control form-control-sm input-sm"%> </div>
        <div class="list-group-item">Anul apariției: <%= select_tag :year, options_for_select(select_year), class: "form-control form-control-sm input-sm"%></div>
        <div class="list-group-item">Gen: <%= select_tag :genre, options_for_select(select_genre), class: "form-control form-control-sm input-sm"%></div>
        <div class="list-group-item">Actori principali: <%= text_field_tag :actors, nil, class: "form-control form-control-sm input-sm"%> </div>
        <div class="list-group-item">Locatii: <%= select_tag :locations, options_for_select(select_location), class: "form-control form-control-sm input-sm"%> </div>
      </div>
    <% end %>

    <br>
    <div class="center-block"> <%= paginate @videos %> </div>

  </div>

  <div class="col-lg-9">
    <br><br>
    <div class="row">
      <% @videos.each do |video| %>
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
          <%= image_tag(video.poster_url, :alt => "", style: "width:252px;height:430px;") %>
          <div class="card-body">
            <h4 class="card-title">
              <%= link_to "#{video.item.name} (#{video.year})", video_path(video) %>
            </h4>
            <p class="card-text"> Rating imdb: <%= video.imdb_rating %> </p>
            <p class="card-text"> Gen: <%= video.genres %></p>
            <p class="card-text"> Actori: <%= video.actors %> </p>

          </div>
          <div class="card-footer">
            <small class="text-muted"><div class="btn-group"><%= button_to "Vezi detalii", video_path(video), method: :get, class: "btn btn-success btn-sm btn-space" %><%= button_to("Imprumuta", item_physical_videos_path(video.item.id), method: :get, class: "btn btn-primary btn-sm") if video.item.physical_items.present? %></div></small>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.col-lg-9 -->

</div>
<!-- /.row -->

app/views/videos/show.html.erb
<div class="container">
<h1 class="my-4"><%= "#{@video.item.name} (#{@video.year})" %></h1>
<div class="row">

  <div class="col-lg-4">
    <br>
    <div class="list-group">
      <%= image_tag(@video.poster_url, :alt => "", style: "width:252px;height:430px;") %>
    </div>

    <br>
    <% unless @video.trailer_url.blank? %>
      <h4> Vizualizeaza trailer: </h4>
      <iframe width="300" height="200" src="<%= "#{@youtube_video}" %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% end %>
  </div>

  <div class="col-lg-8">

    <div class="card card-outline-secondary my-4">
      <div class="card-header">
        Detalii despre film
      </div>
      <div class="card-body">
        <p class="card-text">Data lansarii: <%= Date.parse(@video.released.to_s).strftime("%a, %d %b %Y") %></p>
        <p class="card-text">Tip: <%= @video.category.capitalize %> </p>
        <p class="card-text">Limba: <%= @video.language %> </p>
        <p class="card-text">Genuri: <%= @video.genres %> </p>
        <p class="card-text">Imdb rating: <%= @video.imdb_rating %> </p>
        <hr>
        <p class="card-text">Director: <%= @video.director %></p>
        <p class="card-text">Scriitori: <%= @video.writer %></p>
        <p class="card-text">Actori principali: <%= @video.actors %></p>
        <hr>
        <p class="card-text"> Pagina imdb: <%= link_to "Link", @video.imdb_url %>
        <hr>
        <% if @video.item.physical_items.present? %>
          <p class="card-text">Acest film este disponibil in urmatoarele locatii: </p>
          <% @video.locations.each do |location| %>
            <p class="card-text"><a href="<%=item_physical_videos_path(@video.item.id)%>" class="btn btn-primary">Inchiriaza film</a> - <%= "#{Location.first.name} - #{Location.first.address}" %> </p>
          <% end %>
          <hr>
          Poti vedea toate optiunile aici: <a href="<%=item_physical_videos_path(@video.item.id)%>" class="btn btn-success">Vezi toate optiunile</a>
        <% else %>
          <b>Acest obiect nu mai este disponibil</b>
        <% end %>
      </div>
    </div>

  </div>

</div>
</div>