config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'static_pages#home'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:edit, :update]
  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'

  get 'user_password_resets/new'
  get 'user_password_resets/edit'

  resources :account_activations, only: [:edit]
  resources :user_password_resets, only: [:new, :create, :edit, :update]

  resources :items do
    resources :physical_videos, only: [:index]
  end

  resources :loans, only: [:index]

  resources :physical_item do
    resources :loans, only: [:new]
  end

  resources :loans, only: [:create]

  resources :videos, only: [:index, :show]

  namespace :admin do
    resources :videos, only: [:new, :create, :edit, :update]
    resources :locations, only: [:new, :create, :edit, :update]
  end

  namespace :administrator do
    resources :clients
    resources :users
    resources :items
    resources :videos
    resources :locations
    resources :cities
    resources :global_settings, only: [:edit, :update]
    resources :physical_items
    resources :physical_videos
    resources :loans
    resources :coordinates
  end

  resources :locations, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/admin/physical_videos_controller.rb
class Admin::PhysicalVideosController < ApplicationController
  def new
    @item_id = Item.find(params[:item_id])
    @physical_video = PhysicalVideo.new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/administrator/cities_controller.rb
class Administrator::CitiesController < AdminsController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /administrator/cities
  def index
    @cities = City.all
  end

  # GET /administrator/cities/1
  def show
  end

  # GET /administrator/cities/new
  def new
    @city = City.new
  end

  # GET /administrator/cities/1/edit
  def edit
  end

  # POST /administrator/cities
  def create
    @city = City.new(city_params)

    if @city.save
      redirect_to [:administrator, @city], notice: 'City was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /administrator/cities/1
  def update
    if @city.update(city_params)
      redirect_to [:administrator, @city], notice: 'City was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /administrator/cities/1
  def destroy
    @city.destroy
    redirect_to administrator_cities_url, notice: 'City was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def city_params
      params.require(:city).permit(:id, :name, :coordinate_id, :country)
    end
end

app/controllers/administrator/clients_controller.rb
class Administrator::ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    @q = Client.ransack(params[:q])
    @clients = @q.result.order(updated_at: :desc).page(params[:page])
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to [:administrator, @client], notice: 'Client was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @client.update(client_params)
      redirect_to [:administrator, @client], notice: 'Client was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @client.destroy
    redirect_to administrator_clients_url, notice: 'Client was successfully destroyed.'
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:id, :name, :phone, :address, :unique_identifier_code, :other_information)
    end
end

app/controllers/administrator/coordinates_controller.rb
class Administrator::CoordinatesController < AdminsController
  before_action :set_coordinate, only: [:show, :edit, :update, :destroy]

  # GET /administrator/coordinates
  def index
    @coordinates = Coordinate.all
  end

  # GET /administrator/coordinates/1
  def show
  end

  # GET /administrator/coordinates/new
  def new
    @coordinate = Coordinate.new
  end

  # GET /administrator/coordinates/1/edit
  def edit
  end

  # POST /administrator/coordinates
  def create
    @coordinate = Coordinate.new(coordinate_params)

    if @coordinate.save
      redirect_to [:administrator, @coordinate], notice: 'Coordinate was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /administrator/coordinates/1
  def update
    if @coordinate.update(coordinate_params)
      redirect_to [:administrator, @coordinate], notice: 'Coordinate was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /administrator/coordinates/1
  def destroy
    @coordinate.destroy
    redirect_to administrator_coordinates_url, notice: 'Coordinate was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinate
      @coordinate = Coordinate.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def coordinate_params
      params.require(:coordinate).permit(:id, :longitude, :latitude)
    end
end

app/controllers/administrator/global_settings_controller.rb
class Administrator::GlobalSettingsController < AdminsController
  before_action :set_global_setting, only: %i[edit update]

  def edit; end

  def update
    if @global_setting.update(global_setting_params)
      flash[:success] = 'Global setting was successfully updated.'
      render action: 'edit'
    else
      render action: 'edit'
    end
  end

  private

  def set_global_setting
    @global_setting = GlobalSetting.find(params[:id])
  end

  def global_setting_params
    params.require(:global_setting).permit(:application_name, :maximum_days_for_burrowing, :maximum_items_per_client)
  end
end

app/controllers/administrator/items_controller.rb
class Administrator::ItemsController < AdminsController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /administrator/items
  def index
    @q = Item.ransack(params[:q])
    @items = @q.result.order(updated_at: :desc).page(params[:page])
  end

  # GET /administrator/items/1
  def show
  end

  # GET /administrator/items/new
  def new
    @item = Item.new
  end

  # GET /administrator/items/1/edit
  def edit
  end

  # POST /administrator/items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to [:administrator, @item], notice: 'Item was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /administrator/items/1
  def update
    if @item.update(item_params)
      redirect_to [:administrator, @item], notice: 'Item was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /administrator/items/1
  def destroy
    @item.destroy
    redirect_to administrator_items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:name)
    end
end

app/controllers/administrator/loans_controller.rb
class Administrator::LoansController < AdminsController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  def index
    @q = Loan.ransack(params[:q])
    @loans = @q.result.order(updated_at: :desc).page(params[:page])
  end

  def show
  end

  def new
    @loan = Loan.new
  end

  def edit
  end

  def create
    @loan = Loan.new(loan_params)

    if @loan.save
      flash[:success] = 'Loan was successfully created.'
      redirect_to [:administrator, @loan]
    else
      render action: 'new'
    end
  end

  def update
    if @loan.update(loan_params)
      flash[:success] = 'Loan was successfully updated.'
      redirect_to [:administrator, @loan]
    else
      render action: 'edit'
    end
  end

  def destroy
    @loan.destroy
    redirect_to administrator_loans_url, notice: 'Loan was successfully destroyed.'
  end

  private
    def set_loan
      @loan = Loan.find(params[:id])
    end

    def loan_params
      params.require(:loan).permit(:client_id, :physical_item_id, :burrow_date, :return_date, :status)
    end
end

app/controllers/administrator/locations_controller.rb
class Administrator::LocationsController < AdminsController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /administrator/locations
  def index
    @locations = Location.all
  end

  # GET /administrator/locations/1
  def show
  end

  # GET /administrator/locations/new
  def new
    @location = Location.new
  end

  # GET /administrator/locations/1/edit
  def edit
  end

  # POST /administrator/locations
  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to [:administrator, @location], notice: 'Location was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /administrator/locations/1
  def update
    if @location.update(location_params)
      redirect_to [:administrator, @location], notice: 'Location was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /administrator/locations/1
  def destroy
    @location.destroy
    redirect_to administrator_locations_url, notice: 'Location was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def location_params
      params.require(:location).permit(:name, :address, :schedule, :alternative_contact, :coordinate_id, :city_id)
    end
end

app/controllers/administrator/physical_items_controller.rb
class Administrator::PhysicalItemsController < AdminsController
  before_action :set_physical_item, only: [:show, :edit, :update, :destroy]

  # GET /administrator/physical_items
  def index
    @q = PhysicalItem.ransack(params[:q])
    @physical_items = @q.result.order(updated_at: :desc).page(params[:page])
  end

  # GET /administrator/physical_items/1
  def show
  end

  # GET /administrator/physical_items/new
  def new
    @physical_item = PhysicalItem.new
  end

  # GET /administrator/physical_items/1/edit
  def edit
  end

  # POST /administrator/physical_items
  def create
    @physical_item = PhysicalItem.new(physical_item_params)

    if @physical_item.save
      redirect_to [:administrator, @physical_item], notice: 'Physical item was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /administrator/physical_items/1
  def update
    if @physical_item.update(physical_item_params)
      redirect_to [:administrator, @physical_item], notice: 'Physical item was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /administrator/physical_items/1
  def destroy
    @physical_item.destroy
    redirect_to administrator_physical_items_url, notice: 'Physical item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physical_item
      @physical_item = PhysicalItem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def physical_item_params
      params.require(:physical_item).permit(:id, :item_id, :location_id, :category)
    end
end

app/controllers/administrator/physical_videos_controller.rb
class Administrator::PhysicalVideosController < AdminsController
  before_action :set_physical_video, only: [:show, :edit, :update, :destroy]

  # GET /administrator/physical_videos
  def index
    @q = PhysicalVideo.ransack(params[:q])
    @physical_videos = @q.result.order(updated_at: :desc).page(params[:page])
  end

  # GET /administrator/physical_videos/1
  def show
  end

  # GET /administrator/physical_videos/new
  def new
    @physical_video = PhysicalVideo.new
    @physical_video.build_physical_item
  end

  # GET /administrator/physical_videos/1/edit
  def edit
  end

  # POST /administrator/physical_videos
  def create
    @physical_video = PhysicalVideo.new(physical_video_params)

    if @physical_video.save
      redirect_to [:administrator, @physical_video], notice: 'Physical video was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /administrator/physical_videos/1
  def update
    if @physical_video.update(physical_video_params)
      redirect_to [:administrator, @physical_video], notice: 'Physical video was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /administrator/physical_videos/1
  def destroy
    @physical_video.destroy
    redirect_to administrator_physical_videos_url, notice: 'Physical video was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physical_video
      @physical_video = PhysicalVideo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def physical_video_params
      params.require(:physical_video).permit(:physical_item_id, :is_3d, :format, :resolution, :sound, :dubbed, :other_information, physical_item_attributes: [:location_id, :category, :item_id])
    end
end

app/controllers/administrator/users_controller.rb
class Administrator::UsersController < AdminsController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(updated_at: :desc).page(params[:page])
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to [:administrator, @user], notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to [:administrator, @user], notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to administrator_users_url, notice: 'User was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:id, :client_id, :email, :admin, :city_id, :activated, :activated_at)
    end
end

app/controllers/administrator/videos_controller.rb
class Administrator::VideosController < AdminsController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /administrator/videos
  def index
    @q = Video.ransack(params[:q])
    @videos = @q.result.order(updated_at: :desc).page(params[:page])
  end

  # GET /administrator/videos/1
  def show
  end

  # GET /administrator/videos/new
  def new
    @video = Video.new
  end

  # GET /administrator/videos/1/edit
  def edit
  end

  # POST /administrator/videos
  def create
    @video = Video.new(video_params)

    if @video.save
      redirect_to [:administrator, @video], notice: 'Video was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /administrator/videos/1
  def update
    if @video.update(video_params)
      redirect_to [:administrator, @video], notice: 'Video was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /administrator/videos/1
  def destroy
    @video.destroy
    redirect_to administrator_videos_url, notice: 'Video was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def video_params
      params.require(:video).permit(:item_id, :year, :language, :released, :director, :actors, :writer, :genres, :category, :awards, :rated, :imdb_rating, :imdb_url, :trailer_url, :poster_url)
    end
end

app/controllers/physical_videos_controller.rb
class PhysicalVideosController < ApplicationController
  def index
    @physical_videos = PhysicalVideo.all
                      .filter_location(params[:location_id]&.first)
                      .filter_format(params[:format]&.first)
                      .filter_resolution(params[:resolution]&.first)
                      .filter_is_3d(params[:is_3d]&.first)
    @physical_videos = @physical_videos.joins(:physical_item).where('physical_items.item_id = ?', params[:item_id]).page params[:page]
    @item = Item.find(params[:item_id])
  end
end

app/helpers/admin/physical_videos_helper.rb
module Admin::PhysicalVideosHelper
end

app/helpers/administrator/cities_helper.rb
module Administrator::CitiesHelper
end

app/helpers/administrator/clients_helper.rb
module Administrator::ClientsHelper
end

app/helpers/administrator/coordinates_helper.rb
module Administrator::CoordinatesHelper
end

app/helpers/administrator/global_settings_helper.rb
module Administrator::GlobalSettingsHelper
end

app/helpers/administrator/items_helper.rb
module Administrator::ItemsHelper
end

app/views/administrator/physical_videos/_form.html.erb
<%= form_for([:administrator, @physical_video], html: { class: 'form-horizontal physical_video' }) do |f| %>
  <% if @physical_video.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(@physical_video.errors.count, "error") %> prohibited this physical_video from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% @physical_video.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= f.fields_for :physical_item do |f2| %>
    <div class="form-group">
      <%= f2.label :location_id, class: 'control-label col-md-2'%>
      <div class="col-md-10">
      <%= f2.select :location_id, options_for_select(select_location), class: 'form-control form-control-md' %>
      </div>
    </div>

    <div class="form-group">
      <%= f2.label :item_id, class: 'control-label col-md-2'%>
      <div class="col-md-10">
      <%= f2.number_field :item_id, class: 'form-control' %>
      </div>
    </div>
    <% f2.hidden_field :category, value: "video" %>
  <% end %>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.label :is_3d, for: nil do %>
        <%= f.check_box :is_3d %>
        <%= PhysicalVideo.human_attribute_name(:is_3d) %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :format, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :format, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :resolution, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :resolution, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sound, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :sound, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :dubbed, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :dubbed, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :other_information, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :other_information, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/administrator/physical_videos/edit.html.erb
<div class="page-header">
  <h1>Editing physical_video</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', [:administrator, @physical_video], class: 'btn btn-default' %>
<%= link_to 'Back', administrator_physical_videos_path, class: 'btn btn-default' %>

app/views/administrator/physical_videos/index.html.erb
<div class="page-header">
  <h1>Listing physical_videos</h1>
</div>
<br>
<%= link_to 'New Physical video', new_administrator_physical_video_path, class: 'btn btn-primary' %>

<br><br>
<%= search_form_for @q, url: administrator_physical_items_path do |f| %>

  <%= f.label :id %>
  <%= f.search_field :id_eq, class: "form-control-sm" %>

  <%= f.label :physical_item_id, "Physical Item ID" %>
  <%= f.search_field :physical_item_id, class: "form-control-sm" %>

  <br>
  <%= f.submit 'Search', class: "btn btn-outline-primary btn-sm"%>
  <a href="<%= "#{administrator_physical_videos_url}" %>" class="btn btn-outline-dark btn-sm">Ignore filters</a>
<% end %>

<%= paginate @physical_videos %>
<br>
<%= page_entries_info @physical_videos, entry_name: 'client' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Physical item</th>
      <th>Is 3d</th>
      <th>Format</th>
      <th>Resolution</th>
      <th>Sound</th>
      <th>Dubbed</th>
      <th>Other information</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @physical_videos.each do |physical_video| %>
      <tr>
        <td><%= physical_video.id %></td>
        <td><%= physical_video.physical_item_id %></td>
        <td><%= physical_video.is_3d %></td>
        <td><%= physical_video.format %></td>
        <td><%= physical_video.resolution %></td>
        <td><%= physical_video.sound %></td>
        <td><%= physical_video.dubbed %></td>
        <td><%= physical_video.other_information %></td>
        <td><%= link_to 'Show', [:administrator, physical_video], class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_administrator_physical_video_path(physical_video), class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', [:administrator, physical_video], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/administrator/physical_videos/new.html.erb
<div class="page-header">
  <h1>New physical_video</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', administrator_physical_videos_path, class: 'btn btn-default' %>

app/views/administrator/physical_videos/show.html.erb
<p id="notice"><%= notice %></p>

<dl class="dl-horizontal">
  <dt><strong>Physical item:</strong></dt>
  <dd><%= @physical_video.physical_item_id %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Is 3d:</strong></dt>
  <dd><%= @physical_video.is_3d %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Format:</strong></dt>
  <dd><%= @physical_video.format %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Resolution:</strong></dt>
  <dd><%= @physical_video.resolution %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Sound:</strong></dt>
  <dd><%= @physical_video.sound %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Dubbed:</strong></dt>
  <dd><%= @physical_video.dubbed %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Other information:</strong></dt>
  <dd><%= @physical_video.other_information %></dd>
</dl>

<%= link_to 'Edit', edit_administrator_physical_video_path(@physical_video), class: 'btn btn-default' %>
<%= link_to 'Back', administrator_physical_videos_path, class: 'btn btn-default' %>